[server]
headless = true
address = "0.0.0.0"
port = 8501
enableCORS = false
enableXsrfProtection = false
baseUrlPath = ""

[global]
developmentMode = false

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"
serverPort = 8501
